ignoredBuiltDependencies:
  - cucumber
  - cucumber-expressions
  - cypress
  - es5-ext

onlyBuiltDependencies:
  - '@dhis2/cli-helpers-engine'
  - '@dhis2/cli-style'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild

publicHoistPattern:
  - '@dhis2/ui'
  - typeface-roboto
  - prop-types
  - '@dhis2/d2-i18n'
  - post-robot
  - styled-jsx
  - '@dhis2/app-adapter'
  - '@dhis2/pwa'
  - '@hisptz/dhis2-analytics'
